port: "8000"

db:
  username: "postgres"
  host: "localhost"
  port: "5437"
  dbname: "postgres"
  sslmode: "disable"

nats:
  serverURL: "nats://localhost:4222"
  clusterID: "test-cluster"
  producer: "producer"
  subscriber: "subscriber"
  subject: "order"
